import { useMemo, useState, type ReactNode } from "react";
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, ClipboardCheck, FileClock, Filter, ShieldAlert, Users, X, Zap } from "lucide-react";
import NigeriaProjectMap from "@/components/NigeriaProjectMap";

type FilterState = { date: string; state: string; lga: string; contractor: string; type: string; status: string };
const initialFilters: FilterState = { date: "Last 30 days", state: "All states", lga: "All LGAs", contractor: "All contractors", type: "All project types", status: "All statuses" };
const kpis = [["Total Projects", "1,284", "All projects in programme", "green", Zap], ["Active Projects", "946", "Currently monitored", "teal", Activity], ["Beneficiaries Verified", "941", "Confirmed on site", "green", Users], ["Capacity Verified", "875 kW", "Verified installed capacity", "green", Zap], ["Inspections Pending", "73", "Awaiting field action", "amber", ClipboardCheck], ["Pending REA Verification", "31", "Awaiting final review", "purple", FileClock], ["Projects At Risk", "16", "Require attention", "rose", AlertTriangle]] as const;
const attention = [["Reports awaiting verification", "71", "high"], ["Reports returned by REA", "9", "high"], ["Critical findings", "22", "critical"], ["Overdue inspections", "14", "high"], ["Overdue corrective actions", "14", "high"], ["Projects behind schedule", "27", "neutral"], ["Projects without recent inspection", "31", "neutral"]] as const;
const pipeline = [["Inspection Conducted", "154", "blue"], ["Submitted", "126", "teal"], ["Consultant Approved", "94", "green"], ["Pending REA Review", "71", "amber"], ["REA Verified", "52", "purple"]] as const;
const kpiDetails: Record<string, { label: string; value: string }[]> = {
  "Total Projects": [{ label: "Active projects", value: "946" }, { label: "Pending verification", value: "31" }, { label: "Projects at risk", value: "16" }],
  "Active Projects": [{ label: "Under inspection", value: "73" }, { label: "Verified projects", value: "875" }, { label: "Behind schedule", value: "27" }],
  "Beneficiaries Verified": [{ label: "Confirmed on site", value: "941" }, { label: "Connected communities", value: "612" }, { label: "Awaiting confirmation", value: "329" }],
  "Capacity Verified": [{ label: "Verified capacity", value: "875 kW" }, { label: "Installed projects", value: "875" }, { label: "Pending capacity checks", value: "31" }],
  "Inspections Pending": [{ label: "Awaiting field action", value: "73" }, { label: "Overdue inspections", value: "14" }, { label: "Assigned field officers", value: "31" }],
  "Pending REA Verification": [{ label: "Awaiting final review", value: "31" }, { label: "Submitted reports", value: "71" }, { label: "Average turnaround", value: "2.4 days" }],
  "Projects At Risk": [{ label: "Critical risk", value: "5" }, { label: "High risk", value: "11" }, { label: "Open corrective actions", value: "34" }],
};

function Panel({ title, subtitle, action, children, className = "" }: { title: string; subtitle?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={`executive-panel ${className}`}><header className="executive-panel-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</header>{children}</section>; }
function ActionButton({ children, onClick, tone = "secondary" }: { children: ReactNode; onClick?: () => void; tone?: "primary" | "secondary" }) { return <button className={`executive-action ${tone}`} onClick={onClick}>{children}</button>; }

export default function ReaOverview() {
  const [filters, setFilters] = useState(initialFilters);
  const [applied, setApplied] = useState(initialFilters);
  const [period, setPeriod] = useState("30 Days");
  const [selectedKpi, setSelectedKpi] = useState<string | null>(null);
  const [notice, setNotice] = useState("");
  const activeFilters = useMemo(() => Object.values(applied).filter((value, index) => value !== Object.values(initialFilters)[index]).length, [applied]);
  const updateFilter = (key: keyof FilterState, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const notify = (message: string) => setNotice(message);
  return <section className="executive-overview">
    <header className="executive-header"><div><div className="executive-kicker"><span /> NATIONAL INSPECTION &amp; PROJECT OVERSIGHT</div><h1>Overview</h1></div><div className="executive-freshness"><span><i /> Last updated: Today, 09:40 AM</span><b>1,284 projects · 36 states + FCT</b></div></header>
    <div className="executive-filter-bar"><div className="executive-filter-title"><Filter size={14} /><b>Global filters</b>{activeFilters > 0 && <em>{activeFilters} active</em>}</div>{([["date", "Date range", "Last 30 days"], ["state", "State", "All states"], ["lga", "LGA", "All LGAs"], ["contractor", "Contractor", "All contractors"], ["type", "Project type", "All project types"], ["status", "Project status", "All statuses"]] as const).map(([key, label, defaultValue]) => <label key={key}><span>{label}</span><select value={filters[key]} onChange={(event) => updateFilter(key, event.target.value)}><option>{defaultValue}</option><option>{key === "date" ? "Last 90 days" : key === "state" ? "Kano" : key === "lga" ? "Tarauni" : key === "contractor" ? "GreenVolt Nigeria Ltd" : key === "type" ? "Solar mini-grid" : "At risk"}</option></select></label>)}<button className="filter-clear" onClick={() => { setFilters(initialFilters); setApplied(initialFilters); setNotice("Filters cleared"); }}><X size={12} /> Clear</button><button className="filter-apply" onClick={() => { setApplied(filters); setNotice("Dashboard filters applied"); }}>Apply filters</button></div>
    {notice && <button className="executive-notice" onClick={() => setNotice("")}><CheckCircle2 size={13} /> {notice}<X size={12} /></button>}
    <div className="executive-kpis">{kpis.map(([label, value, detail, tone, Icon]) => <button className={`executive-kpi ${tone} ${selectedKpi === label ? "selected" : ""}`} key={label} onClick={() => setSelectedKpi((current) => current === label ? null : label)}><span><Icon size={16} /></span><small>{label}</small><b>{value}</b><ArrowRight size={13} /></button>)}</div>
    {selectedKpi && <section className="executive-kpi-details"><div><small>{selectedKpi} detail view</small><b>{kpis.find(([label]) => label === selectedKpi)?.[1]}</b></div><div className="executive-kpi-detail-list">{kpiDetails[selectedKpi].map((detail) => <button key={detail.label} onClick={() => notify(`${detail.label}: ${detail.value}`)}><span>{detail.label}</span><b>{detail.value}</b><ArrowRight size={12} /></button>)}</div><button className="executive-kpi-close" onClick={() => setSelectedKpi(null)}><X size={13} /> Close details</button></section>}
    <Panel title="Requires Attention" subtitle="Priority items requiring programme action" action={<ActionButton onClick={() => notify("Attention register opened")}>View all <ArrowRight size={12} /></ActionButton>} className="attention-priority">{attention.map(([label, count, severity]) => <button className="attention-row" key={label} onClick={() => notify(`${label} opened`)}><i className={severity} /><span>{label}</span><b>{count}</b><small>View <ArrowRight size={11} /></small></button>)}</Panel>
    <Panel title="Inspection & Verification Pipeline" subtitle="Status movement through the programme" action={<ActionButton onClick={() => notify("Pipeline reports opened")}>View reports <ArrowRight size={12} /></ActionButton>} className="pipeline-panel"><div className="executive-pipeline">{pipeline.map(([label, count, tone], index) => <div className="pipeline-stage-wrap" key={label}><button className={`pipeline-stage ${tone}`} onClick={() => notify(`${label} reports opened`)}><span>{index + 1}</span><b>{label}</b><strong>{count}</strong></button>{index < pipeline.length - 1 && <ArrowRight className="pipeline-arrow" size={16} />}</div>)}</div><div className="pipeline-bottleneck"><div><ShieldAlert size={15} /><span><b>71 reports are pending REA verification</b><small>Current bottleneck · Average review time: 2.4 days</small></span></div><ActionButton onClick={() => notify("Pending verification reports opened")}>View details</ActionButton></div></Panel>
    <Panel title="Programme Health" subtitle="Executive indicators across the reporting period" className="health-panel"><div className="health-grid">{[["Schedule Performance", "91%", "On track", "green"], ["Inspection Completion Rate", "73%", "Of planned inspections", "blue"], ["REA Verification Rate", "56%", "Of submitted reports", "purple"], ["Compliance Rate", "78.5%", "Across verified projects", "green"], ["Projects With Critical Issues", "22", "Require escalation", "rose"], ["Avg Verification Turnaround", "2.4 days", "Current average", "amber"]].map(([label, value, detail, tone]) => <div className="health-item" key={label}><span>{label}</span><b className={tone}>{value}</b><small>{detail}</small><i><em className={tone} style={{ width: value.includes("days") ? "48%" : value.includes(".") ? "78.5%" : `${Math.min(100, Number.parseInt(value))}%` }} /></i></div>)}</div></Panel>
    <div className="executive-two-col"><Panel title="Project Coverage & Risk" subtitle="Operational coverage and status by location" action={<ActionButton onClick={() => notify("Project Map opened")} tone="primary">Open Project Map <ArrowRight size={12} /></ActionButton>} className="coverage-risk"><div className="executive-map-real"><NigeriaProjectMap compact showLabels={false} showLegend={false} /></div><div className="risk-summary"><b>Geographic Risk Summary</b>{[["Kano", "8 projects at risk", "critical"], ["Kaduna", "6 overdue inspections", "high"], ["Bauchi", "5 critical findings", "critical"], ["Niger", "4 pending verification", "neutral"]].map(([state, detail, tone]) => <button key={state} onClick={() => notify(`${state} risk summary opened`)}><i className={tone} /><span><b>{state}</b> — {detail}</span><ArrowRight size={11} /></button>)}</div></Panel><Panel title="Inspections Over Time" subtitle="Completed, submitted, approved, and verified" action={<select className="period-select" value={period} onChange={(event) => setPeriod(event.target.value)}><option>30 Days</option><option>90 Days</option><option>12 Months</option></select>} className="executive-trend"><div className="trend-chart"><div className="trend-y"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><svg viewBox="0 0 520 180" preserveAspectRatio="none"><path className="trend-green" d="M0 138 C35 126 48 142 75 115 S122 127 150 101 S198 115 225 87 S270 104 301 70 S347 90 375 57 S425 76 451 43 S490 52 520 27" /><path className="trend-blue" d="M0 153 C35 142 49 151 76 133 S123 142 151 119 S198 131 227 112 S271 120 302 98 S348 116 376 83 S425 103 452 70 S490 86 520 61" /><path className="trend-purple" d="M0 164 C37 156 50 161 78 149 S124 157 152 140 S199 149 228 132 S271 141 303 119 S349 136 377 109 S426 126 453 96 S490 112 520 88" /><path className="trend-amber" d="M0 170 C38 166 51 170 79 160 S125 167 153 151 S200 161 229 146 S272 154 304 137 S350 150 378 128 S427 142 454 119 S491 130 520 108" /></svg></div><div className="trend-legend"><span><i className="green" /> Completed</span><span><i className="blue" /> Submitted</span><span><i className="purple" /> Approved</span><span><i className="amber" /> Verified</span></div></Panel></div>
    <div className="executive-two-col"><Panel title="Compliance Overview" subtitle="Distribution across verified projects" action={<ActionButton onClick={() => notify("Compliance report opened")}>View Compliance Report <ArrowRight size={12} /></ActionButton>} className="compliance-panel"><div className="compliance-bar"><i className="green" style={{ width: "72%" }} /><i className="blue" style={{ width: "19%" }} /><i className="amber" style={{ width: "7%" }} /><i className="rose" style={{ width: "2%" }} /></div><div className="compliance-rows">{[["Compliant", "72%", "green"], ["Partially Compliant", "19%", "blue"], ["Non-Compliant", "7%", "amber"], ["Critical", "2%", "rose"]].map(([label, value, tone]) => <div key={label}><i className={tone} /><span>{label}</span><b>{value}</b></div>)}</div></Panel><Panel title="Contractor Performance" subtitle="Top contractors by current programme performance" action={<ActionButton onClick={() => notify("Contractor performance opened")}>View Contractor Performance <ArrowRight size={12} /></ActionButton>} className="contractor-snapshot"><div className="contractor-snapshot-head"><span>CONTRACTOR</span><span>PROJECTS</span><span>COMPLIANCE</span><span>OPEN ISSUES</span></div>{[["ABC Energy", "42", "92%", "3"], ["XYZ Power", "31", "84%", "7"], ["GreenGrid", "28", "79%", "9"], ["Arewa Solar Concepts", "24", "76%", "6"]].map((row) => <button className="contractor-snapshot-row" key={row[0]} onClick={() => notify(`${row[0]} profile opened`)}><b>{row[0]}</b><span>{row[1]}</span><strong>{row[2]}</strong><em>{row[3]}</em></button>)}</Panel></div>
    <Panel title="Critical Findings" subtitle="Latest high-risk programme findings" action={<ActionButton onClick={() => notify("All critical findings opened")}>View All Critical Findings <ArrowRight size={12} /></ActionButton>} className="findings-panel"><div className="executive-findings-head"><span>FINDING ID</span><span>PROJECT</span><span>FINDING</span><span>SEVERITY</span><span>STATUS</span><span>REPORTED DATE</span></div>{[["CF-2026-00122", "Kano Solar Mini Grid", "Installation issue", "Critical", "Open", "24 May 2026"], ["CF-2026-00118", "Kaduna Rural Electrification", "Safety non-compliance", "Critical", "Under Review", "23 May 2026"], ["CF-2026-00115", "Bauchi Mini Grid", "Equipment failure", "Major", "Under Review", "22 May 2026"]].map((row) => <button className="executive-finding-row" key={row[0]} onClick={() => notify(`${row[0]} details opened`)}>{row.map((cell, index) => <span key={`${row[0]}-${index}`} className={index === 3 ? `finding-${cell.toLowerCase()}` : index === 4 ? "finding-status" : ""}>{cell}</span>)}</button>)}</Panel>
    <Panel title="Recent Activity" subtitle="Meaningful workflow actions across the programme" action={<ActionButton onClick={() => notify("Activity log opened")}>View All Activity <ArrowRight size={12} /></ActionButton>} className="activity-panel"><div className="executive-activity">{[["Consultant", "approved inspection AIR-2026-00482", "2 min ago", "green"], ["Field Officer", "submitted inspection AIR-2026-00483", "15 min ago", "blue"], ["REA Admin", "verified project REA-KN-2026-0044", "35 min ago", "green"], ["Consultant", "requested re-inspection AIR-2026-00466", "1 hr ago", "amber"], ["Contractor", "completed corrective action CA-2026-0011", "2 hrs ago", "purple"]].map((item) => <div key={item[1]}><i className={item[3]} /><span><b>{item[0]}</b> {item[1]}</span><small>{item[2]}</small></div>)}</div></Panel>
  </section>;
}
